import { useEffect, useMemo, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Sky } from "@react-three/drei";
import { createXRStore, XR, XROrigin, useXR } from "@react-three/xr";
import { ACESFilmicToneMapping } from "three";
import {
  GreatHall, TeachingBlock, EntranceMonument, Shrine, ParkingCanopy, SportsField,
  ConstructionBlock,
} from "./CampusBuildings";
import { useGLTF } from "@react-three/drei";
import { PalmPlant, type PlantLook } from "./GrovePlants";
import { grassTexture, metresRepeat } from "../lib/groundTexture";
import { paveTexture } from "../lib/campusTexture";
import type { Building } from "../buildings";

/**
 * A single **building's page** — the building on its own, turning slowly on a
 * paved apron, with its name, what it is for, and how it is built. Opened by
 * tapping the building in the site scene.
 *
 * Same three view modes as everywhere else: Normal for a low-end phone, Ultra
 * for a capable one, and VR (which always presents Ultra).
 */
type ViewMode = "normal" | "ultra";

function detectViewMode(): ViewMode {
  if (typeof navigator === "undefined") return "ultra";
  const cores = navigator.hardwareConcurrency ?? 4;
  const mem = (navigator as Navigator & { deviceMemory?: number }).deviceMemory ?? 4;
  const small = typeof window !== "undefined" && Math.min(window.screen.width, window.screen.height) < 500;
  return cores <= 4 || mem <= 3 || small ? "normal" : "ultra";
}

/** One paving tile-set per 8 m of ground → roughly 1 m slabs. */
const PAVER_M = 8;

const PALM_LOOK: PlantLook = { form: "palm", leaf: "#3f8a44", leaf2: "#57a052", bark: "#9a7b4a" };

/**
 * A building generated by `scripts/generate-building.mjs` from a JSON spec —
 * the no-3D-skills route in docs/BUILDINGS.md. Landmarks are hand-authored
 * components instead; this is for ordinary blocks, where fifteen numbers and a
 * photograph are the whole contribution.
 */
function GeneratedBuilding({ model }: { model: string }) {
  const { scene } = useGLTF(`/models/${model}.glb`);
  const copy = useMemo(() => {
    const c = scene.clone(true);
    c.traverse((o) => { o.castShadow = true; o.receiveShadow = true; });
    return c;
  }, [scene]);
  return <primitive object={copy} />;
}

/** Draw just this building, centred on the origin. */
function TheBuilding({ id, model }: { id: string; model?: string }) {
  if (model) return <GeneratedBuilding model={model} />;
  switch (id) {
    case "hall": return <GreatHall position={[0, 0, 0]} />;
    case "teaching": return <TeachingBlock position={[0, 0, 0]} w={45} d={15} floors={4} />;
    case "gate": return <EntranceMonument position={[0, 0, 0]} rotation={Math.PI} />;
    case "shrine": return <Shrine position={[0, 0, 0]} />;
    case "construction": return <ConstructionBlock position={[0, 0, 0]} w={46} d={18} floors={5} />;
    case "parking":
      return (
        <>
          {[-1, 1].map((i) => (
            <ParkingCanopy key={i} position={[i * 12, 0, 0]} rotation={Math.PI / 2} length={92} width={10} solar />
          ))}
        </>
      );
    case "field": return <SportsField position={[0, 0, 0]} w={120} d={75} />;
    default: return null;
  }
}

export function BuildingView({
  building, onBack, onBackToMap, backLabel = "← Back",
}: {
  building: Building;
  onBack: () => void;
  onBackToMap: () => void;
  /**
   * A building page is reached either from its site or straight from the
   * Buildings directory, so the caller names the step back rather than this
   * guessing and getting it wrong half the time.
   */
  backLabel?: string;
}) {
  const store = useMemo(() => createXRStore({ emulate: false }), []);
  const [vrSupported, setVrSupported] = useState(false);
  const [mode, setMode] = useState<ViewMode>(detectViewMode);
  const [spin, setSpin] = useState(true);
  // The info sheet is most of a phone screen, and the building is the point of
  // the page. It opens by default — you arrive wanting to know what this is —
  // but it has to get out of the way in one tap.
  const [info, setInfo] = useState(true);

  useEffect(() => {
    const xr = (navigator as Navigator & { xr?: { isSessionSupported(m: string): Promise<boolean> } }).xr;
    xr?.isSessionSupported("immersive-vr").then(setVrSupported).catch(() => setVrSupported(false));
  }, []);

  // Frame from the footprint, not just the height — a long low block needs far
  // more room than a tall narrow one. Keep the eye low so we read the facade
  // rather than the roof, and aim high so the info sheet doesn't cover it.
  //
  // The distance has to come off the *horizontal* field of view, which on a
  // portrait phone is far narrower than the 45° vertical one: at a 0.64 aspect
  // it is only ~29°. Sizing off height alone put a 62 m building half outside
  // the frame on a phone while looking fine on a laptop.
  const dist = useMemo(() => {
    const aspect = Math.min(2.2, Math.max(0.45, window.innerWidth / window.innerHeight));
    const halfV = Math.tan((45 * Math.PI) / 360);
    const halfH = Math.atan(halfV * aspect);
    const forSpan = (building.spanM * 0.5) / Math.tan(halfH) * 1.12;
    const forHeight = (building.heightM * 0.6) / halfV;
    return Math.max(forSpan, forHeight, 26);
  }, [building.spanM, building.heightM]);
  const eye = Math.max(4, building.heightM * 0.5);
  // The orbit target lands at the centre of the viewport, so everything ABOVE it
  // in world space draws above centre. Aiming high therefore pushes the building
  // DOWN the screen, straight behind the info sheet — the opposite of what the
  // old comment here claimed. Aim low while the sheet is open so the building
  // sits in the clear band above it, and re-centre when the sheet is dismissed.
  const aim = Math.max(2.5, building.heightM * (info ? 0.34 : 0.5));

  return (
    <div className="building">
      <Canvas
        dpr={mode === "normal" ? [1, 1.5] : [1, 2]}
        camera={{ position: [dist * 0.5, eye, dist], fov: 45, near: 0.5, far: 900 }}
        gl={{ antialias: mode === "ultra", powerPreference: "high-performance" }}
        shadows={mode === "ultra"}
        onCreated={({ gl }) => {
          gl.toneMapping = ACESFilmicToneMapping;
          gl.toneMappingExposure = 1.15;
        }}
      >
        <XR store={store}>
          <Sky sunPosition={[120, 70, 60]} turbidity={5} rayleigh={1} mieCoefficient={0.005} mieDirectionalG={0.92} />
          <fog attach="fog" args={["#cfe0e8", 200, 700]} />
          <ambientLight intensity={0.55} />
          <hemisphereLight args={["#cfe2ff", "#6b8a45", 0.8]} />
          <directionalLight
            position={[80, 70, 50]}
            intensity={2.3}
            color="#fff1d6"
            castShadow={mode === "ultra"}
            shadow-mapSize={[2048, 2048]}
            shadow-bias={-0.0006}
            shadow-camera-far={300}
            shadow-camera-left={-90}
            shadow-camera-right={90}
            shadow-camera-top={90}
            shadow-camera-bottom={-90}
          />
          <Ground />
          <TheBuilding id={building.id} model={building.model} />
          {/* a pair of palms for scale, hidden for teaching block to avoid clipping */}
          {building.id !== "teaching" && [-1, 1].map((s) => (
            <group key={s} position={[s * (dist * 0.42), 0, dist * 0.18]}>
              <PalmPlant look={PALM_LOOK} height={11} seed={s + 3} opacity={1} wind={mode === "ultra" ? 1 : 0} />
            </group>
          ))}
          <XROrigin position={[0, 0, dist * 0.8]} />
          <VrImpliesUltra onEnter={() => setMode("ultra")} />
          <OrbitControls
            enablePan={false}
            minDistance={Math.max(12, building.spanM * 0.5)}
            maxDistance={dist * 2.6}
            maxPolarAngle={Math.PI / 2.12}
            enableDamping
            target={[0, aim, 0]}
            autoRotate={spin}
            autoRotateSpeed={0.5}
          />
        </XR>
      </Canvas>

      <div className="cls-top">
        <button className="backbtn" onClick={onBack}>{backLabel}</button>
        <span className="cls-title">🏛️ {building.name}</span>
        <button
          className="grove-quality"
          onClick={() => setMode((m) => (m === "ultra" ? "normal" : "ultra"))}
          title="View mode — Normal is the low-end baseline, Ultra is the full 3D scene"
        >
          {mode === "ultra" ? "✨ Ultra" : "🍃 Normal"}
        </button>
        {vrSupported && (
          <button className="vr-btn cls-vr" onClick={() => { setMode("ultra"); store.enterVR(); }}>🥽 VR</button>
        )}
      </div>

      <button className="bld-spin" onClick={() => setSpin((v) => !v)}>
        {spin ? "⏸ Stop turning" : "▶ Turn"}
      </button>

      {!info && (
        <button className="bld-show" onClick={() => setInfo(true)}>
          ℹ️ About this building
        </button>
      )}

      <div className={`bld-panel${info ? "" : " bld-panel--hidden"}`} aria-hidden={!info}>
        <div className="bld-head">
          <b>{building.name}</b>
          <span className="khmer">{building.khmer}</span>
          <button
            className="bld-hide"
            onClick={() => setInfo(false)}
            aria-label="Hide the description and see the building"
            title="Hide"
          >
            ✕
          </button>
        </div>
        <div className="bld-sub">
          {building.english}{building.site ? ` · ${building.site}` : ""}
        </div>
        {building.about.map((p) => (
          <p key={p.slice(0, 24)} className="bld-about">{p}</p>
        ))}
        <ul className="bld-facts">
          {building.facts.map((f) => (
            <li key={f.label}><span>{f.label}</span><b>{f.value}</b></li>
          ))}
        </ul>
        <p className="bld-note">
          Modelled from photographs of the real building — the massing is an informed
          approximation, not survey data. Corrections welcome.
        </p>
        <div className="bld-actions">
          <button className="bld-map" onClick={onBackToMap}>← Back to the map</button>
          <button className="bld-hide-btn" onClick={() => setInfo(false)}>Hide</button>
        </div>
      </div>
    </div>
  );
}

function Ground() {
  const grass = useMemo(() => grassTexture(30), []);
  const pave = useMemo(() => paveTexture(metresRepeat(156, 156, PAVER_M)[0]), []);
  return (
    <>
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.06, 0]} receiveShadow>
        <planeGeometry args={[900, 900]} />
        <meshStandardMaterial map={grass} roughness={1} />
      </mesh>
      {/* the apron sits over the lawn — offset so the two can't fight for depth */}
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, 0.05, 0]} receiveShadow>
        <circleGeometry args={[78, 48]} />
        <meshStandardMaterial
          map={pave} roughness={1}
          polygonOffset polygonOffsetFactor={-2} polygonOffsetUnits={-2}
        />
      </mesh>
    </>
  );
}

function VrImpliesUltra({ onEnter }: { onEnter: () => void }) {
  const inXR = useXR((s) => s.session != null);
  useEffect(() => { if (inXR) onEnter(); }, [inXR, onEnter]);
  return null;
}
